{% set name = "map_parallel" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/map-parallel-{{ version }}.tar.gz
  sha256: 9bcf4390c4e508f6e028217164f92cd1ccde73f33ea412064cf9dbd115491ec2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - map_parallel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ickc/python-map_parallel
  summary: A drop-in replacement of map/starmap but in parallel with different backends.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
